### ISSUE TITLE
purge shader cache 

### ISSUE THREAD

**Issue by ghost** [elardramora/Code-Bobykit#2]
Salut  boss,  

L'utilisateur  peut sans soucis purger les shaders par lui-même,  il est possibles également que les shaders vulkan soit pas notamment le nombre inital vue qu'il dépende des drivers  et carte graphique utiliser (même si nvidia)

**Comment by elardramora** [comment]
Yo ! Je sais bien Bobynou 😇Mais jaime l'idée de pouvoir le faire depuis l'exe si l'user à mis un level d'option trop haut et redescend en option ✌️Envoyé depuis mon téléphone Orange-------- Message original --------De : sakuka47 ***@***.***>Date : mar. 30 mai 2023 à 20:30À : elardramora/Code-Bobykit ***@***.***>Cc : Subscribed ***@***.***>Objet : [elardramora/Code-Bobykit] purge shader cache  (Issue #2)
Salut  boss,
L'utilisateur  peut sans soucis purger les shaders par lui-même,  il est possibles également que les shaders vulkan soit pas notamment le nombre inital vue qu'il dépende des drivers  et carte graphique utiliser (même si nvidia)
